
info:
  app:
    name: user-service
    version: 1.0.1
  build:
    artifactId: user-service
    version: '@version@'
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
mybatis:
  configLocation: classpath:mybatis-config.xml
  mapperLocations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.study.user.entity.*
server:
  port: 8080


