
info:
  app:
    name: user-service
    version: 1.0.1
  build:
    artifactId: user-service
    version: '@version@'
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  resources:
    static-locations:
      - classpath:/static
#i18n setting
  messages:
     basename: i18n/gateway/admin/messages,i18n/common/messages
     cache-duration: 3600s
     encoding: UTF-8

mybatis:
  configLocation: classpath:mybatis-config.xml
  mapperLocations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.study.gateway.admin.entity.*
server:
  port: 8080


