package com.study.user.mapper.sys;

import com.study.user.entity.sys.SysPermissionRole;

public interface SysPermissionRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbg.generated
     */
    int insert(SysPermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbg.generated
     */
    int insertSelective(SysPermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbg.generated
     */
    SysPermissionRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysPermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysPermissionRole record);
}