spring:
  application:
  name: ch4-gateway
  cloud:
    gateway:
    routes:
      - id: service1_v1
      uri: http://localhost:8081/v1
      predicates:
        - Path=/test
        - Weight=service1, 95
      - id: service1_v2
      uri: http://localhost:8081/v2
      predicates:
       - Path=/test
       - Weight=service1, 5