
info:
  app:
    name: OSS
    version: 1.0.1
  build:
    artifactId: logistics-app-oss
    version: '@version@'
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  configLocation: classpath:mybatis-config.xml
  mapperLocations: classpath*:mapper/**/*.xml
  typeAliasesPackage: tk.mapper.model
server:
  port: 8080
