
server:
  port: 9000
spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin
  profiles:
    active: dev
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}:${random.long(1,100)}
    appname: eureka-server